language: php

php:
  - 7.4snapshot

# Shallow clones can cause issues with subtree splits
git:
    depth: false

services:
  - memcached
  - redis-server

before_install:
  - echo "extension=memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - printf "\n" | pecl install -f redis

before_script:
  - composer self-update
  - composer install
  - composer dump-autoload -o

script:
  - vendor/bin/phpunit --verbose
  #- composer run-script lint-check

deploy:
  - provider: script
    script: bash bin/split.sh $TRAVIS_BRANCH $GIT_USER $GIT_ACCESS_TOKEN
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^(develop|1.1|master)$
    skip_cleanup: true

notifications:
  email:
    - dave@opulencephp.com

sudo: false

matrix:
  fast_finish: true
